matcha_drink/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('tentang_kami/', include('tentangkami.urls')),
    path('menu/', include('menu.urls')),
    path('testimonial/', include('testimonial.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('cart/<int:cart_id>', views.cart_detail, name='cart')
]

tentangkami/urls.py
from django.urls import path
from . import views

app_name = 'tentangkami'

urlpatterns = [
    path('', views.tentang_kami, name='tentangkami'),
]

testimonial/urls.py
from django.urls import path
from . import views

app_name = 'testimonial'

urlpatterns = [
    path('', views.testimonial, name='testimonial'),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
]

menu/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    description = models.TextField()
    favorite = models.BooleanField(default=False)
    image = models.FileField(upload_to='menu/')

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        all_orders = []
        for order in self.order_set.all():
            all_orders.append(str(order))

        return '{}: {}'.format(self.user, ', '.join(all_orders))


class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{} {}'.format(self.amount, self.menu)

tentangkami/models.py
from django.db import models

# Create your models here.
class EmailModel(models.Model):
    email = models.CharField(max_length = 50)

testimonial/models.py
from django.db import models

# Create your models here.
class Testimonial(models.Model):
    name = models.CharField(max_length=50, blank=False)
    message = models.CharField(max_length=300, blank=False)

web/models.py
from django.db import models

from menu.models import Menu

# Create your models here.
class UserVisit(models.Model):
    user = models.CharField(max_length=50)

    def __str__(self):
        return self.user

class FavoriteMenu(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    image = models.FileField(upload_to='web/')

menu/forms.py
from django import forms

from .models import Menu, Order

class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for menu in Menu.objects.all():
            self.fields['menu_' + str(menu.id)] = forms.IntegerField(
                min_value=0,
                max_value=32767,
                initial=0,
            )

    def clean(self):
        super().clean()

        total = 0
        for value in self.cleaned_data.values():
            total += value
        if total == 0:
            raise forms.ValidationError('Harus pesan minimal 1 minuman.')

tentangkami/forms.py
from django import forms

class EmailForms(forms.Form):
    email = forms.CharField(max_length = 50)

testimonial/forms.py
from django import forms

class TestimoniForm(forms.Form):
    name = forms.CharField(label="Nama", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Masukkan Nama Anda',
        'required': True,
    }))

    message = forms.CharField(label="Testimoni", widget=forms.Textarea(attrs={
        'rows': 6,
        'style': 'resize:none;',
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Testimoninya :)',
        'required': True,
    }))

web/forms.py
from django import forms

from .models import UserVisit

class User(forms.Form):
    user_name = forms.CharField(
        label='Siapa Namamu?',
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        ),
    )

menu/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import OrderForm
from .models import Cart, Menu, Order


# Create your views here.
def menu(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            user = request.session.get('user_name')
            if user is not None:
                cart = Cart(user=user)
            else:
                cart = Cart(user='user')

            cart.save()
            for key, value in form.cleaned_data.items():
                if key[:5] == 'menu_' and int(value) > 0:
                    order = Order(
                        cart=cart,
                        menu=get_object_or_404(Menu, id=key[5:]),
                        amount=value,
                    )
                    order.save()

            return redirect(reverse('menu:cart', kwargs={'cart_id': cart.id}))

    else:
        form = OrderForm()

    favorite_menu = Menu.objects.filter(favorite=True)
    for each in favorite_menu:
        each.form_field = form['menu_' + str(each.id)]

    other_menu = Menu.objects.filter(favorite=False)
    for each in other_menu:
        each.form_field = form['menu_' + str(each.id)]

    context = {
        'favorite_menu': favorite_menu,
        'other_menu': other_menu,
        'form': form,
    }

    return render(request, 'menu/menu.html', context)


def cart_detail(request, cart_id):
    cart = get_object_or_404(Cart, id=cart_id)
    all_orders = cart.order_set.all()

    subtotal = 0
    for order in all_orders:
        subtotal += order.amount * order.menu.price

    context = {
        'orders': cart.order_set.all(),
        'subtotal': subtotal,
    }

    return render(request, 'menu/cart.html', context)

tentangkami/views.py
from django.shortcuts import render,redirect
from .forms import EmailForms
from .models import EmailModel

# Create your views here.
def tentang_kami(request):   
    form = EmailForms(request.POST or None)
    if request.method == 'POST':
        model = EmailModel(email = form['email'].value())
        model.save()
        return redirect("tentangkami:tentangkami")
    else:
        return render(request,"index.html", {'generated_form': form})

testimonial/views.py
from django.shortcuts import render
from .models import Testimonial
from .forms import TestimoniForm

# Create your views here.
def testimonial(request):
    responses = {}
    if request.method == "POST":
        form = TestimoniForm(request.POST)
        if form.is_valid():
            testimonial = Testimonial()
            testimonial.name = form.cleaned_data['name']
            testimonial.message = form.cleaned_data['message']
            testimonial.save()
        responses['form'] = form
        responses['data'] = Testimonial.objects.all()[::-1][:5]
        return render(request, 'testimonial/testimonial.html', responses)
    form = TestimoniForm()
    responses['form'] = form
    responses['data'] = Testimonial.objects.all()[::-1][:5]
    return render(request, 'testimonial/testimonial.html', responses)

web/views.py
from django.shortcuts import render, redirect

from .models import FavoriteMenu, UserVisit
from .forms import User

# Create your views here.
def index(request):

    if request.method == 'POST':
        form_user = User(request.POST)
        if form_user.is_valid():
            form = UserVisit()
            user = form_user.cleaned_data['user_name']
            form.save()

            request.session['user_name'] = user

    favorite_menu_home = FavoriteMenu.objects.filter(menu__favorite=True)
    form_user = User()
    context = {
        'favorite_menu_home' : favorite_menu_home,
        'form_user' : form_user,
    }
    return render(request, 'web/index.html', context)

menu/templates/menu/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
<link rel="stylesheet" href="{% static 'menu/cart.css' %}">
{% endblock %}

{% block content %}
<section id="cart">
  <div>
    <h1>Pesanan</h1>
    <div class="card p-4 my-4">
      <div class="container-fluid">
        {% for order in orders %}
        <div class="row align-items-center my-3">
          <div class="col-4 col-md-2">
            <img class="image" src="{{ order.menu.image.url }}">
          </div>
          <div class="name col-8 col-md-6">
            {{ order.menu.name }}
          </div>
          <div class="col-4 col-md-1 text-right">
            {{ order.amount }}
          </div>
          <div class="col-8 col-md-3">
            Rp {{ order.menu.price|intcomma }}
          </div>
        </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <div id="subtotal" class="py-3 px-4 b-darkgreen d-flex flex-column flex-md-row">
            <div>
            Subtotal
            </div>
            <div class="ml-md-5">
              Rp {{ subtotal|intcomma }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="buttons mt-4">
      <a href="{% url 'menu:menu' %}" class="button b-green">Pesan</a>
      <a href="{% url 'menu:menu' %}" class="button b-white">Kembali</a>
    </div>
  </div>
</section>
{% endblock %}

menu/templates/menu/menu.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
<link rel="stylesheet" href="{% static 'menu/menu.css' %}">
<style>
.btn-plus {
  background-image: url("{% static 'menu/count_plus.svg' %}");
  right: 0;
}
.btn-min {
  background-image: url("{% static 'menu/count_min.svg' %}");
  left: 0;
}
</style>
{% endblock %}

{% block content %}
<section id="header" class="d-flex b-green position-relative">
  <div class="d-flex align-items-center position-relative z-1">
    <h1>Yuk Pesan</h1>
  </div>
  <img src="{% static 'menu/menu_photo.png' %}" class="position-absolute">
</section>
<section id="menu">
  <div>
    <form method="POST">
      {% csrf_token %}
      {{ form.errors }}
      <div class="menu">
        <h1>Menu Favorit</h1>
        <div class="container-fluid">
          {% for menu in favorite_menu %}
          <div class="row align-items-center">
            <div class="col-6 col-md-2">
              <img src="{{ menu.image.url }}">
            </div>
            <div class="col-6 col-md-2">
              <span class="name">{{ menu.name }}</span>
              <br>
              <span class="price">Rp {{ menu.price|intcomma }}</span>
            </div>
            <div class="desc col-6 col-md-5">
              {{ menu.description }}
            </div>
            <div class="col-6 col-md-3">
              <div class="input-number position-relative">
                <button onclick="this.parentNode.querySelector('input').stepDown()" class="btn-min"></button>
                {{ menu.form_field }}
                <button onclick="this.parentNode.querySelector('input').stepUp()" class="btn-plus"></button>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="menu">
        <h1>Menu Lainnya</h1>
        <div class="container-fluid">
          {% for menu in other_menu %}
          <div class="row align-items-center">
            <div class="col-6 col-md-2">
              <img src="{{ menu.image.url }}">
            </div>
            <div class="col-6 col-md-2">
              <span class="name">{{ menu.name }}</span>
              <br>
              <span class="price">Rp {{ menu.price|intcomma }}</span>
            </div>
            <div class="desc col-6 col-md-5">
              {{ menu.description }}
            </div>
            <div class="col-6 col-md-3">
              <div class="input-number position-relative">
                <button onclick="this.parentNode.querySelector('input').stepDown()" class="btn-min"></button>
                {{ menu.form_field }}
                <button onclick="this.parentNode.querySelector('input').stepUp()" class="btn-plus"></button>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="my-5">
        <button type="submit" class="button b-green">Pesan</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

{% block script %}
<script>
$('form').on('click', 'button:not([type="submit"])', function(e){
  e.preventDefault();
})
</script>
{% endblock %}

tentangkami/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'tentangkami/css/tentangkami.css' %}">
{% endblock %}
{% block content %} 
<section id="header" class="d-flex b-green position-relative" style="margin-bottom: 20px;">
    <div class="d-flex align-items-center position-relative z-1">
        <h1>Tentang <br>Kami</h1>
    </div>  
    <img src="{% static 'tentangkami/lamp.png' %}" class="position-absolute">
</section>
  
<section>
    <div class="row" style="margin-top: 80px;">
        <div class="col-md-5" >
            <img src="{% static 'tentangkami/coffee.jpg'%}" alt="FotoKopi" style="height: 82%; width: 100%;">
        </div>
        <div class="col-md-7 ">
            <p style="font-size: 3rem;">Cerita Kami</p>
            <p style="font-size: 1rem;" >MatchA Drink merupakan sebuah startup retail minuman yang ingin menyajikan minuman high quality untuk para pelanggannya. 
                Nama MatchA Drink yang diambil dari Match A Drink yang berarti para pelanggan dapat memesan minuman sebebasnya . Kami ingin eksistensi kami akan membuat standar baru minuman berkualitas untuk konsumen.
                MatchA Drink dibuat dari hasil pemikiran kami tentang minuman yang dapat dipesan online. </p>
        </div>
    </div> 
    
    <div class ="row" style="margin-bottom: 60px;">
        <div class ="col-sm">
            <form method="POST">
                <h1>Lebih Dekat dengan Kami!</h1>
                <p for ="input">Berlangganan <i>Newsletter</i> kami</p>
                {% csrf_token %}
                {{ generated_form.email }}
                <div class="mt-2">
                    <button class ="button b-green" type="submit" id="input">Yay!</button>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock %}

testimonial/templates/testimonial/testimonial.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'testimonial/style.css' %}">
{% endblock %}

{% block content %}
<section id="header" class="d-flex b-green position-relative">
    <div class="d-flex align-items-center position-relative z-1">
        <h1>Testimoni</h1>
    </div>
    <img src="{% static 'testimonial/testimonial_photo.png' %}" class="position-absolute">
</section>
<section id="testimonial" class="d-flex flex-column flex-md-row">
    <div class="row">
        <div class="col-md">
            <div class="col-mw">
                <form action='' method="POST">
                    {% csrf_token %}
                    {{ form.name.label_tag }}
                    {{ form.name }}
                    <br>
                    {{ form.message.label_tag }}
                    {{ form.message }}
                    <br>
                    <input type="submit" class="button b-green" value="Submit">
                </form>
            </div>
        </div>
        <div class="col-md flex-row">
            {% for object in data %}
            <div class="card b-green mb-2 w-100">
                <h2>
                    {{ object.name }}
                </h2>
                <p>
                    {{ object.message }}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
</section> 
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Match'A Drink{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block style %}{% endblock %}
  </head>
  <body>
    <div id="container" class="position-relative">
      <!-- Navbar -->
      <div class="fixed-top bg-white">
        <nav class="navbar navbar-default navbar-expand-md navbar-light">
          <a class="navbar-brand" href="{% url 'web:index' %}">Match'A Drink</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="ml-auto navbar-nav">
              {% with url_name=request.resolver_match.url_name %}
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'index' %} active{% endif %}" href="{% url 'web:index' %}">Beranda</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'menu' %} active{% endif %}" href="{% url 'menu:menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'tentang' %} active{% endif %}" href="{% url 'tentangkami:tentangkami'%}">Tentang Kami</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'testimoni' %} active{% endif %}" href="{% url 'testimonial:testimonial' %}">Testimoni</a>
              </li>
              {% endwith %}
            </ul>
          </div>
        </nav>
      </div>
      <!-- Content -->
      {% block content %}{% endblock %}
      <!-- Footer -->
      <footer class="position-absolute b-darkgreen d-flex justify-content-center align-items-center">
        <div class="font-weight-bold">
          © Lulus Pepew Aamiin 2019
        </div>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
  </body>
</html>

web/templates/web/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
<link rel="stylesheet" href="{% static 'homepage/homepage.css' %}">
<style>
    .btn-selengkapnya {
        background-image: url("{% static 'homepage/selengkapnya.svg' %}");
        left: 0;
    }
</style>
{% endblock %}

{% block content %}
<section id="header" class="d-flex b-green position-relative">
  <div class="d-flex align-items-center position-relative z-1">
    <h1>
        Cari,
        <br>
        Pesan,
        <br>
        Minum.
    </h1>
  </div>

  <img src="{% static 'homepage/homepage_photo.png' %}" class="position-absolute">
</section>
<section id="homepage">

    <div>
        <div class="container-fluid">
            <div class="homepage">
                <h1>Menu Favorit</h1>

                <div class="row">
                    {% for fav in favorite_menu_home %}
                    <div class="col">
                        <div class="card">
                            <img src="{{ fav.image.url }}">
                                <div class="desc-card">
                                <h3>{{ fav.menu.name }}</h3>
                                <h5>Rp {{ fav.menu.price|intcomma }}</h5>
                                {{ fav.menu.description }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col align-items-center">
                        <div class="card">
                            <div class="card-body text-center">
                                <h3>Lihat <br> Selengkapnya</h3>
                                <a href="{% url 'menu:menu' %}">
                                    <button type="submit" class="btn-selengkapnya text-center"></button>
                                </a>
                            </div>
                            <div class="">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% if not request.session.user_name %}
<div class="position-fixed w-100 h-100 fixed-top">
    <div class="input">
        <form class="" action="{% url 'web:index' %}" method="POST">
            <div class="card-user align-items-center">
                {% csrf_token %}
                <!-- {{ form_user }} -->
                {{ form_user.user_name.label }}
                {{ form_user.user_name }}
                <input type="submit" class="button b-green" value="Oke">
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}